export const STUDY_SUBJECTS = [
  "General study",
  "Accounting",
  "Finance",
  "Economics",
  "Business Studies",
  "Management",
  "Marketing",
  "Mathematics",
  "Statistics",
  "Data Analytics",
  "Computer Science",
  "Physics",
  "Chemistry",
  "Biology",
  "Engineering",
  "Law",
  "Psychology",
  "Sociology",
  "History",
  "Literature",
  "Medicine",
  "Nursing",
  "Professional Certification",
  "Other",
] as const;
